controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_8
      - joint_9
      - joint_10
      - joint_11
      - joint_12
    
    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"] 
    interpolation_method: splines
    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: false
    open_loop_control: false

    constraints:
      goal_time: 3.0
      stopped_velocity_tolerance: 0.05
    
    action_monitor_rate: 20.0
